### ISSUE TITLE
Update documentation for custom CA certs

### ISSUE THREAD

**Issue by tiran** [wbolster/dotfiles#5]
## Debian/Ubuntu

* ``/usr/share/ca-certificates`` is reserved for files managed by package managers
* user customization should be placed in ``/usr/local/share/ca-certificates``
* mention that CA certificate must have ``.crt`` extension
* ``/sbin/update-ca-certificates`` is easier to remember than dpkg reconfigure

## Fedora/CentOS/RHEL

* place certificate in ``/etc/pki/ca-trust/source/anchors/``
* run ``update-ca-trust``

**Comment by wbolster** [comment]
thanks, my notes were for personal use after some experimentation, and apparently not perfect 🙃 thanks for them feedback, that's very educational
